// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// IBDMatrix
IntegerMatrix IBDMatrix(CharacterVector chromosomes, NumericVector positions_bp, int number_pairs, IntegerVector ibd_pairs_colnumbers, CharacterVector ibd_chromosomes, NumericVector ibd_start_bp, NumericVector ibd_stop_bp);
RcppExport SEXP XIBD_IBDMatrix(SEXP chromosomesSEXP, SEXP positions_bpSEXP, SEXP number_pairsSEXP, SEXP ibd_pairs_colnumbersSEXP, SEXP ibd_chromosomesSEXP, SEXP ibd_start_bpSEXP, SEXP ibd_stop_bpSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type chromosomes(chromosomesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type positions_bp(positions_bpSEXP);
    Rcpp::traits::input_parameter< int >::type number_pairs(number_pairsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ibd_pairs_colnumbers(ibd_pairs_colnumbersSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ibd_chromosomes(ibd_chromosomesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ibd_start_bp(ibd_start_bpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ibd_stop_bp(ibd_stop_bpSEXP);
    __result = Rcpp::wrap(IBDMatrix(chromosomes, positions_bp, number_pairs, ibd_pairs_colnumbers, ibd_chromosomes, ibd_start_bp, ibd_stop_bp));
    return __result;
END_RCPP
}
// calculateMissingness
NumericVector calculateMissingness(IntegerMatrix genotypes);
RcppExport SEXP XIBD_calculateMissingness(SEXP genotypesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    __result = Rcpp::wrap(calculateMissingness(genotypes));
    return __result;
END_RCPP
}
// calculatePopAlleleFreq
NumericVector calculatePopAlleleFreq(IntegerMatrix genotypes, IntegerVector chromosomes, IntegerVector genders);
RcppExport SEXP XIBD_calculatePopAlleleFreq(SEXP genotypesSEXP, SEXP chromosomesSEXP, SEXP gendersSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type chromosomes(chromosomesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type genders(gendersSEXP);
    __result = Rcpp::wrap(calculatePopAlleleFreq(genotypes, chromosomes, genders));
    return __result;
END_RCPP
}
// groupPairs
CharacterMatrix groupPairs(CharacterVector group);
RcppExport SEXP XIBD_groupPairs(SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type group(groupSEXP);
    __result = Rcpp::wrap(groupPairs(group));
    return __result;
END_RCPP
}
// calculateHaplotypeFreq
NumericMatrix calculateHaplotypeFreq(IntegerMatrix genotypes, IntegerMatrix condition_snps_0, IntegerVector genders, const int chromosome, Function polyrootR);
RcppExport SEXP XIBD_calculateHaplotypeFreq(SEXP genotypesSEXP, SEXP condition_snps_0SEXP, SEXP gendersSEXP, SEXP chromosomeSEXP, SEXP polyrootRSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type condition_snps_0(condition_snps_0SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type genders(gendersSEXP);
    Rcpp::traits::input_parameter< const int >::type chromosome(chromosomeSEXP);
    Rcpp::traits::input_parameter< Function >::type polyrootR(polyrootRSEXP);
    __result = Rcpp::wrap(calculateHaplotypeFreq(genotypes, condition_snps_0, genders, chromosome, polyrootR));
    return __result;
END_RCPP
}
// haplotypeToGenotype
IntegerMatrix haplotypeToGenotype(IntegerMatrix haplotypes, IntegerVector chromosomes, IntegerVector genders);
RcppExport SEXP XIBD_haplotypeToGenotype(SEXP haplotypesSEXP, SEXP chromosomesSEXP, SEXP gendersSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type haplotypes(haplotypesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type chromosomes(chromosomesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type genders(gendersSEXP);
    __result = Rcpp::wrap(haplotypeToGenotype(haplotypes, chromosomes, genders));
    return __result;
END_RCPP
}
// IBDLabel
IntegerVector IBDLabel(IntegerVector snp_id, const int number_snps);
RcppExport SEXP XIBD_IBDLabel(SEXP snp_idSEXP, SEXP number_snpsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type snp_id(snp_idSEXP);
    Rcpp::traits::input_parameter< const int >::type number_snps(number_snpsSEXP);
    __result = Rcpp::wrap(IBDLabel(snp_id, number_snps));
    return __result;
END_RCPP
}
// isolatePairs
CharacterMatrix isolatePairs(CharacterVector fid, CharacterVector iid);
RcppExport SEXP XIBD_isolatePairs(SEXP fidSEXP, SEXP iidSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type fid(fidSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type iid(iidSEXP);
    __result = Rcpp::wrap(isolatePairs(fid, iid));
    return __result;
END_RCPP
}
// calculate_viterbi_m1
IntegerVector calculate_viterbi_m1(const int noStates, NumericVector piProb, int meiosis, const int NoSNPs, IntegerMatrix genotypes, NumericVector alleleFreq, NumericVector positionM, double error, int gender1, int gender2, int chrom);
RcppExport SEXP XIBD_calculate_viterbi_m1(SEXP noStatesSEXP, SEXP piProbSEXP, SEXP meiosisSEXP, SEXP NoSNPsSEXP, SEXP genotypesSEXP, SEXP alleleFreqSEXP, SEXP positionMSEXP, SEXP errorSEXP, SEXP gender1SEXP, SEXP gender2SEXP, SEXP chromSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type noStates(noStatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type piProb(piProbSEXP);
    Rcpp::traits::input_parameter< int >::type meiosis(meiosisSEXP);
    Rcpp::traits::input_parameter< const int >::type NoSNPs(NoSNPsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alleleFreq(alleleFreqSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type positionM(positionMSEXP);
    Rcpp::traits::input_parameter< double >::type error(errorSEXP);
    Rcpp::traits::input_parameter< int >::type gender1(gender1SEXP);
    Rcpp::traits::input_parameter< int >::type gender2(gender2SEXP);
    Rcpp::traits::input_parameter< int >::type chrom(chromSEXP);
    __result = Rcpp::wrap(calculate_viterbi_m1(noStates, piProb, meiosis, NoSNPs, genotypes, alleleFreq, positionM, error, gender1, gender2, chrom));
    return __result;
END_RCPP
}
// calculate_gamma_m1
NumericMatrix calculate_gamma_m1(const int noStates, NumericVector piProb, int meiosis, const int NoSNPs, IntegerMatrix genotypes, NumericVector alleleFreq, NumericVector positionM, double error, int gender1, int gender2, int chrom);
RcppExport SEXP XIBD_calculate_gamma_m1(SEXP noStatesSEXP, SEXP piProbSEXP, SEXP meiosisSEXP, SEXP NoSNPsSEXP, SEXP genotypesSEXP, SEXP alleleFreqSEXP, SEXP positionMSEXP, SEXP errorSEXP, SEXP gender1SEXP, SEXP gender2SEXP, SEXP chromSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type noStates(noStatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type piProb(piProbSEXP);
    Rcpp::traits::input_parameter< int >::type meiosis(meiosisSEXP);
    Rcpp::traits::input_parameter< const int >::type NoSNPs(NoSNPsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alleleFreq(alleleFreqSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type positionM(positionMSEXP);
    Rcpp::traits::input_parameter< double >::type error(errorSEXP);
    Rcpp::traits::input_parameter< int >::type gender1(gender1SEXP);
    Rcpp::traits::input_parameter< int >::type gender2(gender2SEXP);
    Rcpp::traits::input_parameter< int >::type chrom(chromSEXP);
    __result = Rcpp::wrap(calculate_gamma_m1(noStates, piProb, meiosis, NoSNPs, genotypes, alleleFreq, positionM, error, gender1, gender2, chrom));
    return __result;
END_RCPP
}
// calculate_viterbi_m2
IntegerVector calculate_viterbi_m2(const int noStates, NumericVector piProb, int meiosis, const int NoSNPs, IntegerMatrix genotypes, NumericVector alleleFreq, NumericVector positionM, double error, int gender1, int gender2, int chrom, IntegerVector conditionSNPs, NumericMatrix haplotypeFreq);
RcppExport SEXP XIBD_calculate_viterbi_m2(SEXP noStatesSEXP, SEXP piProbSEXP, SEXP meiosisSEXP, SEXP NoSNPsSEXP, SEXP genotypesSEXP, SEXP alleleFreqSEXP, SEXP positionMSEXP, SEXP errorSEXP, SEXP gender1SEXP, SEXP gender2SEXP, SEXP chromSEXP, SEXP conditionSNPsSEXP, SEXP haplotypeFreqSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type noStates(noStatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type piProb(piProbSEXP);
    Rcpp::traits::input_parameter< int >::type meiosis(meiosisSEXP);
    Rcpp::traits::input_parameter< const int >::type NoSNPs(NoSNPsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alleleFreq(alleleFreqSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type positionM(positionMSEXP);
    Rcpp::traits::input_parameter< double >::type error(errorSEXP);
    Rcpp::traits::input_parameter< int >::type gender1(gender1SEXP);
    Rcpp::traits::input_parameter< int >::type gender2(gender2SEXP);
    Rcpp::traits::input_parameter< int >::type chrom(chromSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type conditionSNPs(conditionSNPsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type haplotypeFreq(haplotypeFreqSEXP);
    __result = Rcpp::wrap(calculate_viterbi_m2(noStates, piProb, meiosis, NoSNPs, genotypes, alleleFreq, positionM, error, gender1, gender2, chrom, conditionSNPs, haplotypeFreq));
    return __result;
END_RCPP
}
// calculate_gamma_m2
NumericMatrix calculate_gamma_m2(const int noStates, NumericVector piProb, int meiosis, const int NoSNPs, IntegerMatrix genotypes, NumericVector alleleFreq, NumericVector positionM, double error, int gender1, int gender2, int chrom, IntegerVector conditionSNPs, NumericMatrix haplotypeFreq);
RcppExport SEXP XIBD_calculate_gamma_m2(SEXP noStatesSEXP, SEXP piProbSEXP, SEXP meiosisSEXP, SEXP NoSNPsSEXP, SEXP genotypesSEXP, SEXP alleleFreqSEXP, SEXP positionMSEXP, SEXP errorSEXP, SEXP gender1SEXP, SEXP gender2SEXP, SEXP chromSEXP, SEXP conditionSNPsSEXP, SEXP haplotypeFreqSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type noStates(noStatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type piProb(piProbSEXP);
    Rcpp::traits::input_parameter< int >::type meiosis(meiosisSEXP);
    Rcpp::traits::input_parameter< const int >::type NoSNPs(NoSNPsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alleleFreq(alleleFreqSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type positionM(positionMSEXP);
    Rcpp::traits::input_parameter< double >::type error(errorSEXP);
    Rcpp::traits::input_parameter< int >::type gender1(gender1SEXP);
    Rcpp::traits::input_parameter< int >::type gender2(gender2SEXP);
    Rcpp::traits::input_parameter< int >::type chrom(chromSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type conditionSNPs(conditionSNPsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type haplotypeFreq(haplotypeFreqSEXP);
    __result = Rcpp::wrap(calculate_gamma_m2(noStates, piProb, meiosis, NoSNPs, genotypes, alleleFreq, positionM, error, gender1, gender2, chrom, conditionSNPs, haplotypeFreq));
    return __result;
END_RCPP
}
// bVectorHH
IntegerVector bVectorHH(IntegerMatrix genotypes);
RcppExport SEXP XIBD_bVectorHH(SEXP genotypesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    __result = Rcpp::wrap(bVectorHH(genotypes));
    return __result;
END_RCPP
}
// AmatrixHH
NumericMatrix AmatrixHH(NumericVector pop_allele_freqs, IntegerMatrix genotypes);
RcppExport SEXP XIBD_AmatrixHH(SEXP pop_allele_freqsSEXP, SEXP genotypesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type pop_allele_freqs(pop_allele_freqsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    __result = Rcpp::wrap(AmatrixHH(pop_allele_freqs, genotypes));
    return __result;
END_RCPP
}
// bVectorHD
IntegerVector bVectorHD(IntegerMatrix genotypes);
RcppExport SEXP XIBD_bVectorHD(SEXP genotypesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    __result = Rcpp::wrap(bVectorHD(genotypes));
    return __result;
END_RCPP
}
// AmatrixHD
NumericMatrix AmatrixHD(NumericVector pop_allele_freqs, IntegerMatrix genotypes);
RcppExport SEXP XIBD_AmatrixHD(SEXP pop_allele_freqsSEXP, SEXP genotypesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type pop_allele_freqs(pop_allele_freqsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    __result = Rcpp::wrap(AmatrixHD(pop_allele_freqs, genotypes));
    return __result;
END_RCPP
}
// bVectorDD
IntegerVector bVectorDD(IntegerMatrix genotypes);
RcppExport SEXP XIBD_bVectorDD(SEXP genotypesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    __result = Rcpp::wrap(bVectorDD(genotypes));
    return __result;
END_RCPP
}
// AmatrixDD
NumericMatrix AmatrixDD(NumericVector pop_allele_freqs, IntegerMatrix genotypes);
RcppExport SEXP XIBD_AmatrixDD(SEXP pop_allele_freqsSEXP, SEXP genotypesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type pop_allele_freqs(pop_allele_freqsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    __result = Rcpp::wrap(AmatrixDD(pop_allele_freqs, genotypes));
    return __result;
END_RCPP
}
// topbotChange
IntegerMatrix topbotChange(IntegerMatrix Genotypes, CharacterVector topbot);
RcppExport SEXP XIBD_topbotChange(SEXP GenotypesSEXP, SEXP topbotSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type Genotypes(GenotypesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type topbot(topbotSEXP);
    __result = Rcpp::wrap(topbotChange(Genotypes, topbot));
    return __result;
END_RCPP
}
